### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JorgeL** [lopesdasilva/OLD-etoile-webclient#11]
No menu de um curso, em vez de "Summary" pôr "Contents"

**Comment by lopesdasilva** [comment]
Então não era Description?
isto já foi corrigido para description, ainda não foi é posto online.

**Comment by JorgeL** [comment]
"Era" Description, mas entretanto achei melhor Contents...

Eu sei, é preciso ter paciência...

**Comment by lopesdasilva** [comment]
Corrigido no próximo update.
