### ISSUE TITLE
Bug no "Save & Exit"

### ISSUE THREAD

**Issue by JorgeL** [lopesdasilva/OLD-etoile-webclient#16]
Há um bug no save de um teste, parece que não grava a resposta à 1ª questão.

**Comment by lopesdasilva** [comment]
Não consigo reproduzir este bug.
Tentei com um user já existente escrever na primeira pergunta do teste HG e guardar - Tudo Ok.
Tentei com um user totalmente novo no mesmo teste (HG), demorou um pouco mais a gravar mas - Tudo Ok.

**Comment by JorgeL** [comment]
Ok. Vou tentar pelo meu lado, se não conseguirmos reproduzir o erro esperamos que se repita com o Jeff.
