### ISSUE TITLE
checkResults com OneChoice e MultipleChoice

### ISSUE THREAD

**Issue by JorgeL** [lopesdasilva/OLD-etoile-webclient#6]
adicionar as respostas às perguntas de OneChoice e MultipleChoice quando é chamado o checkResults - De momento só está feito para OpenAnswer

**Comment by Rpaixao** [comment]
OneChoice tambem ja sao adicionados à lista no CheckResults.

**Comment by lopesdasilva** [comment]
No webapp já está tudo pronto para o update final.

**Comment by Rpaixao** [comment]
MultipleChoice tambem ja sao adicionados à lista no CheckResults.
