### ISSUE TITLE
Apagar News

### ISSUE THREAD

**Issue by JorgeL** [lopesdasilva/OLD-etoile-webclient#8]
Um prof pode apagar as suas news, e o administrador pode apagar todas

**Comment by Rpaixao** [comment]
Neste momento, tal como tinhamos falado, as NEWS nao estao directamente ligadas a nenhum professor em particular. Desta forma, proponho que todos os professores possam apagar/adicionar news. Mais tarde teremos que pensar numa forma de cada utilizador tar associado `as suas news e so' os seus alunos as verem.

**Comment by Rpaixao** [comment]
A api ja esta preparada para remover news. Falta desenvolver no WEBClient-Professor.

**Comment by JorgeL** [comment]
Acho bem que neste momento todos os professores possam apagar/adicionar news.
